db: tango-host-databaseds-test.ci-ska-tango-archiver-master-low.svc.techops.internal.skao.int:10000
manager: low-eda/cm/01
archiver: low-eda/es/01
configuration:
  - class: TangoTest
    attributes:
      short_scalar_ro:
        archive_period: 5000
        polling_period: 3000
      double_image:
        archive_period: 5000
        polling_period: 3000
