apiVersion: v2
name: ska-tmc-simulators
description: A subchart for SKA-TMC-Simulators  deployment.
type: application
version: 0.0.2
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Team Sahyadri and Himalaya
    email: telmgt-internal@googlegroups.com
dependencies:
- name: ska-tango-base
  version: 0.3.17
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
- name: ska-tango-util
  version: 0.3.17
  repository: https://artefact.skao.int/repository/helm-internal
