display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: TMC-simulators
telescope: SKA-mid
subsystem: ska-tmc-simulators

labels:
  app: ska_tmc_simulators
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  retry:
    - "--tries=10"
    - "--sleep=5"

tmcsim:
  registry: artefact.skao.int
  image: ska-tmc-simulators
  tag: 0.0.6
  pullPolicy: IfNotPresent

# subarray_count, this will be expanded (1 to N inclusive) and applied to instances of:
# deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
subarray_devices:
  - "cspsubarraysimulator"
  - "sdpsubarraysimulator"
subarray_count: 3

dsconfig:
  configuration_file: data/configuration.json
  timeout: 300s
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.5
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.9
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  cspmastersimulator:
    enabled: true
    instances: ["01"]
    file: "data/cspmastersimulator.yaml"
  sdpmastersimulator:
    enabled: false
    instances: ["01"]
    file: "data/sdpmastersimulator.yaml"
  cspsubarraysimulator:
    enabled: false
    instances: ["01", "02", "03"]
    file: "data/cspsubarraysimulator.yaml"
  sdpsubarraysimulator:
    enabled: false
    instances: ["01", "02", "03"]
    file: "data/sdpsubarraysimulator.yaml"
