apiVersion: v2
name: ska-tmc-simulators-umbrella
description: An umbrella Helm chart for SKA-TMC-SIMULATORS deployment.
type: application
version: 0.0.1
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Aditya Dange
    email: adityadange.ska@gmail.com
  - name: Bhushan Parakh
    email: bhushan.ska@gmail.com
dependencies:
- name: ska-tango-base
  version: 0.3.17
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-util
  version: 0.3.17
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tmc-simulators
  version: 0.0.1
  repository: file://../ska-tmc-simulators
