apiVersion: v2
name: ska-tmc-simulators-umbrella
description: An umbrella Helm chart for SKA-TMC-SIMULATORS deployment.
type: application
version: 0.0.3
appVersion: 1.17.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
  - name: Team Sahyadri and Himalaya
    email: telmgt-internal@googlegroups.com
dependencies:
- name: ska-tango-base
  version: 0.4.9
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-util
  version: 0.4.10
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tmc-simulators
  version: 0.0.3
  repository: file://../ska-tmc-simulators
